import random

titulos_termotanques = [
    "❎❎TERMOTANQUES VENTAS POR MAYOR Y MENOR  Escorial señorial❎❎",
    "🌀🌀TERMOTANQUES VENTAS POR MAYOR Y MENOR ESCORIAL SEÑORIAL🌀🌀",
    "🌐🌐termotanques señorial escorial Ventas por mayor y menor🌐🌐",
    "👻👻TERMOTANQUES señorial escorial electronico multigas VENTA POR MAYOR Y MENOR👻👻",
    "🌊🌐LIQUIDAMOS TERMOTANQUES SEÑORIAL ESCORIAL ELECTRONICO Y MULTIGAS 🌐🌊",
    "🔱🌀APROVECHE OFERTA LIMITADA termotanques señorial escorial 🌀⚜",
    "🌀🔱APROVECHE OFERTAS LIMITADAS termotanques señorial escorial electronico multigas 🔱🌀",
    "🌀🌀liquidamos termotanques señorial escorial electronico y multigas 🌀🌀",
    "🌀🌀últimas unidades termotanques señorial escorial electronico multiga 🌀🌀",
    "🔱🔱termotanques señorial escorial precios por mayor y menor 🔱🔱",
    "❇🌐señorial escorial liquidamos termotanques electronico y multigas 🌐❇",
    "👻🔱precios imperdibles Termotanques señorial escorial electronico multigas NUEVOS 👻🔱",
    "💫💫OFERTAS EXCLUSIVAS TERMOTANQUES ESCORIAL SEÑORIAL PRECIOS IMPERDIBLES💫💫",
    "🚿🚿PROMOCIONES TERMOTANQUES SEÑORIAL ESCORIAL ELECTRONICO Y MULTIGASS🚿🚿",
    "💧💧OPORTUNIDAD IMPERDIBLE TERMOTANQUES ESCORIAL SEÑORIAL 💧💧",
    "🚿💧HASTA AGOTAR STOCK TERMOTANQUES ESCORIAL SEÑORIAL 💧🚿",
    "🌊🌊TERMOTANQUES ESCORIAL Y SEÑORIAL OPORTUNIDAD UNICA🌊🌊",
    "🌊🌊termotanques escorial y señorial oportunidad única🌊🌊",
    "🚿💧hasta agotar stock termotanques escorial señorial 💧🚿",
    "💧💧oportunidad imperdible termotanques escorial señorial 💧💧",
    "🚿🚿promociones termotanques señorial escorial electronico y a gas🚿🚿",
    "💫💫ofertas exclusivas termotanques escorial señorial precios imperdibles💫💫",
    "💫💫Ofertas EXCLUSIVAS TERMOTANQUES ESCORIAL SEÑORIAL PRECIOS IMPERDIBLES💫💫",
    "🚿🚿Promociones TERMOTANQUES SEÑORIAL ESCORIAL ELECTRONICO Y MULTIGAS🚿🚿",
    "💧💧Oportunidad IMPERDIBLE TERMOTANQUES ESCORIAL SEÑORIAL 💧💧",
    "🚿💧Hasta Agotar STOCK TERMOTANQUES ESCORIAL SEÑORIAL 💧🚿",
    "🌊🌊Termontanques ESCORIAL Y SEÑORIAL OPORTUNIDAD UNICA🌊🌊",
    "🌊🌊Termotanques escorial y señorial oportunidad única🌊🌊",
    "🚿💧Hasta Agotar stock termotanques escorial señorial 💧🚿",
    "💧💧Oportunidad!! imperdible termotanques escorial señorial 💧💧",
    "🚿🚿Promociones!! termotanques señorial escorial electronico y a gas🚿🚿",
    "💫💫Ofertas!! exclusivas termotanques escorial señorial precios imperdibles💫💫",
    "🍁💫TERMOTANQUES Eléctricos Multigas Señorial Escorial NUEVOS CON garantía LIQUIDAMOS 🍁✨️",
    "👻🔱PRECIOS IMPERDIBLES TERMOTANQUES SEÑORIAL ESCORIAL ELECTRONICO MULTIGAS NUEVOS 👻🔱",
    "❇🌐señorial escorial liquidamos termotanques electronico y multigas 🌐❇",
    "❇🌐SEÑORIAL ESCORIAL LIQUIDAMOS TERMOTANQUES ELECTRONICO Y MULTIGAS 🌐❇",
    "🔱🔱TERMOTANQUES SEÑORIAL ESCORIAL PRECIOS POR MAYOR Y MENOR 🔱🔱",
    "🌀🌀ÚLTIMAS UNIDADES TERMOTANQUES SEÑORIAL ESCORIAL ELECTRONICO MULTIGA 🌀🌀",
    "🌀🌀LIQUIDAMOS TERMOTANQUES SEÑORIAL ESCORIAL ELECTRONICO Y MULTIGAS 🌀🌀",
    "🌀🔱APROVECHE OFERTAS LIMITADAS TERMOTANQUES SEÑORIAL ESCORIAL ELECTRONICO MULTIGAS 🔱🌀",
    "☀☀LIQUIDAMOS TERMOTANQUES SEÑORIAL ESCORIAL NUEVOS OFERTA!!☀☀",
    "🔥🔥TERMOTANQUES ELECTRONICO MULTIGAS SEÑORIAL ESCORIAL NUEVOS VENTA POR MAYOR Y MENOR🔥🔥",
    "🌎🌎VENTA MINORISTA Y MAYORISTA TERMOTANQUES ELECTRONICO MULTIGAS 🌎🌎",
    "💥💥VENTA POR MAYOR Y MENOR TERMOTANQUES ELECTRONICO MULTIGAS 💥💥",
    "🌟🌟TERMOTANQUES ELECTRONICO MULTIGAS SEÑORIAL ESCORIAL NUEVOS CON GARANTIA 🌟🌟",
    "☀☀liquidamos termotanques señorial escorial nuevos oferta!!☀☀",
    "🔥🔥termotanques electronico multigas señorial escorial nuevos venta por mayor y menor🔥🔥",
    "🌎🌎venta minorista y mayorista termotanques electronico multigas 🌎🌎",
    "💥💥venta por mayor y menor termotanques electronico multigas 💥💥",
    "🌟🌟termotanques electronico multigas señorial escorial nuevos con garantia 🌟🌟"]

titulos_aires = ["🌀🌀LIQUIDAMOS AIRES ACONDICIONADOS SAMSUNG HITACHI TCL ENOVA PHILCO 🌀🌀",
                "❎❎AIRES ACONDICIONADOS OFERTAS!! HASTA AGOTAR STOCK❎❎",
                "🌀🌀AIRES ACONDICIONADOS LIQUIDAMOS HASTA AGOTAR STOCK🌀🌀",
                "🌐🌐ULTIMAS UNIDADES AIRES ACONDICIONADOS SAMSUNG HITACHI TCL ENOVA PHILCO...🌐🌐",
                "👻👻AIRES ACONDICIONADOS SAMSUNG HITACHI TCL ENOVA PHILCO OFERTA IMPERDIBLE👻👻",
                "🌊🌐LIQUIDAMOS AIRES ACONDICIONADOS LAS MEJORES MARCAS AL MEJOR PRECIO 🌐🌊",
                "🔱🌀APROVECHE OFERTA LIMITADA AIRES ACONDICIONADOS 🌀⚜",
                "🌀🌀liquidamos aires acondicionados samsung hitachi tcl enova philco 🌀🌀",
                "❎❎aires acondicionados ofertas!! hasta agotar stock❎❎",
                "🌀🌀aires acondicionados liquidamos hasta agotar stock🌀🌀",
                "🌐🌐ultimas unidades aires acondicionados samsung hitachi tcl enova philco...🌐🌐",
                "👻👻aires acondicionados samsung hitachi tcl enova philco oferta imperdible👻👻",
                "🌊🌐liquidamos aires acondicionados las mejores marcas al mejor precio 🌐🌊",
                "🔱🌀aproveche oferta limitada aires acondicionados 🌀⚜",
                "🔱🔱AIRES ACONDICIONADOS OFERTAS EXCLUSIVAS🔱🔱",
                "💫💫Ofertas Exclusivas Aires Acondicionados Eco Invert Split Portatil💫💫",
                "💫💫Aproveche Liquidacion de Aires Acondicionados Eco Invert 💫💫",
                "💫💫ofertas exclusivas aires acondicionados eco invert split portatil💫💫",
                "💫💫aproveche liquidacion de aires acondicionados eco invert 💫💫",
                "💫💫OFERTAS EXCLUSIVAS AIRES ACONDICIONADOS ECO INVERT SPLIT PORTATIL💫💫",
                "💫💫APROVECHE LIQUIDACION DE AIRES ACONDICIONADOS ECO INVERT 💫💫",
                "💫💫OFERTAS EXCLUSIVAS AIRES ACONDICIONADOS ECO INVERT SPLIT PORTATIL💫💫",
                "💫💫APROVECHE LIQUIDACION DE AIRES ACONDICIONADOS ECO INVERT 💫💫"]

titulos_tanques = [
    "❎❎COMBOS TANQUES DE AGUA VENTAS POR MAYOR Y MENOR  Rotoplas forteplas❎❎",
    "🌀🌀COMBOS TANQUES DE AGUA VENTAS POR MAYOR Y MENOR ROTOPLAS FORTEPLAS🌀🌀",
    "🌐🌐combo tanques de agua forteplas rotoplas Ventas por mayor y menor🌐🌐",
    "👻👻COMBOS TANQUES DE AGUA forteplas rotoplas 2, 3 y 4 capas VENTA POR MAYOR Y MENOR👻👻",
    "🌊🌐LIQUIDAMOS COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS 2, 3 y 4 CAPAS Y 🌐🌊",
    "🔱🌀APROVECHE OFERTA LIMITADA combo tanques de agua forteplas rotoplas 🌀⚜",
    "🌀🔱APROVECHE OFERTAS LIMITADAS combo tanques de agua forteplas rotoplas 2, 3 y 4 capas 🔱🌀",
    "🌀🌀liquidamos combo tanques de agua forteplas rotoplas 2, 3 y 4 capas y 🌀🌀",
    "🌀🌀últimas unidades combo tanques de agua forteplas rotoplas 2, 3 y 4 capas🌀🌀",
    "🔱🔱combo tanques de agua forteplas rotoplas precios por mayor y menor 🔱🔱",
    "❇🌐forteplas rotoplas liquidamos combo tanques de agua 2, 3 y 4 capas y 🌐❇",
    "👻🔱precios imperdibles Termotanques forteplas rotoplas 2, 3 y 4 capas NUEVOS 👻🔱",
    "💫💫OFERTAS EXCLUSIVAS COMBOS TANQUES DE AGUA ROTOPLAS FORTEPLAS PRECIOS IMPERDIBLES💫💫",
    "🚿🚿PROMOCIONES COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS 2, 3 y 4 CAPAS YS🚿🚿",
    "💧💧OPORTUNIDAD IMPERDIBLE COMBOS TANQUES DE AGUA ROTOPLAS FORTEPLAS 💧💧",
    "🚿💧HASTA AGOTAR STOCK COMBOS TANQUES DE AGUA ROTOPLAS FORTEPLAS 💧🚿",
    "🌊🌊COMBOS TANQUES DE AGUA ROTOPLAS Y FORTEPLAS OPORTUNIDAD UNICA🌊🌊",
    "🌊🌊combo tanques de agua rotoplas y forteplas oportunidad única🌊🌊",
    "🚿💧hasta agotar stock combo tanques de agua rotoplas forteplas 💧🚿",
    "💧💧oportunidad imperdible combo tanques de agua rotoplas forteplas 💧💧",
    "🚿🚿promociones combo tanques de agua forteplas rotoplas 2, 3 y 4 capas y a gas🚿🚿",
    "💫💫ofertas exclusivas combo tanques de agua rotoplas forteplas precios imperdibles💫💫",
    "💫💫Ofertas EXCLUSIVAS COMBOS TANQUES DE AGUA ROTOPLAS FORTEPLAS PRECIOS IMPERDIBLES💫💫",
    "🚿🚿Promociones COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS 2, 3 y 4 CAPAS Y🚿🚿",
    "💧💧Oportunidad IMPERDIBLE COMBOS TANQUES DE AGUA ROTOPLAS FORTEPLAS 💧💧",
    "🚿💧Hasta Agotar STOCK COMBOS TANQUES DE AGUA ROTOPLAS FORTEPLAS 💧🚿",
    "🌊🌊Termontanques ROTOPLAS Y FORTEPLAS OPORTUNIDAD UNICA🌊🌊",
    "🌊🌊Termotanques rotoplas y forteplas oportunidad única🌊🌊",
    "🚿💧Hasta Agotar stock combo tanques de agua rotoplas forteplas 💧🚿",
    "💧💧Oportunidad!! imperdible combo tanques de agua rotoplas forteplas 💧💧",
    "🚿🚿Promociones!! combo tanques de agua forteplas rotoplas 2, 3 y 4 capas y a gas🚿🚿",
    "💫💫Ofertas!! exclusivas combo tanques de agua rotoplas forteplas precios imperdibles💫💫",
    "🍁💫COMBOS TANQUES DE AGUA Rotoplas NUEVOS CON garantía LIQUIDAMOS 🍁✨️",
    "👻🔱PRECIOS IMPERDIBLES COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS 2, 3 y 4 CAPAS NUEVOS 👻🔱",
    "❇🌐forteplas rotoplas liquidamos combo tanques de agua 2, 3 y 4 capas y 🌐❇",
    "❇🌐FORTEPLAS ROTOPLAS LIQUIDAMOS COMBOS TANQUES DE AGUA 2, 3 y 4 CAPAS Y 🌐❇",
    "🔱🔱COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS PRECIOS POR MAYOR Y MENOR 🔱🔱",
    "🌀🌀ÚLTIMAS UNIDADES COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS 2, 3 y 4 CAPAS🌀🌀",
    "🌀🌀LIQUIDAMOS COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS 2, 3 y 4 CAPAS Y 🌀🌀",
    "🌀🔱APROVECHE OFERTAS LIMITADAS COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS 2, 3 y 4 CAPAS 🔱🌀",
    "☀☀LIQUIDAMOS COMBOS TANQUES DE AGUA FORTEPLAS ROTOPLAS NUEVOS OFERTA!!☀☀",
    "🔥🔥COMBOS TANQUES DE AGUA 2, 3 y 4 CAPAS FORTEPLAS ROTOPLAS NUEVOS VENTA POR MAYOR Y MENOR🔥🔥",
    "🌎🌎VENTA MINORISTA Y MAYORISTA COMBOS TANQUES DE AGUA 2, 3 y 4 CAPAS🌎🌎",
    "💥💥VENTA POR MAYOR Y MENOR COMBOS TANQUES DE AGUA 2, 3 y 4 CAPAS 💥💥",
    "🌟🌟COMBOS TANQUES DE AGUA 2, 3 y 4 CAPAS FORTEPLAS ROTOPLAS NUEVOS CON GARANTIA 🌟🌟",
    "☀☀liquidamos combo tanques de agua forteplas rotoplas nuevos oferta!!☀☀",
    "🔥🔥combo tanques de agua 2, 3 y 4 capas forteplas rotoplas nuevos venta por mayor y menor🔥🔥",
    "🌎🌎venta minorista y mayorista combo tanques de agua 2, 3 y 4 capas 🌎🌎",
    "💥💥venta por mayor y menor combo tanques de agua 2, 3 y 4 capas 💥💥",
    "🌟🌟combo tanques de agua 2, 3 y 4 capas forteplas rotoplas nuevos con garantia 🌟🌟"]

titulos_cocinas = ["🌀🌀LIQUIDAMOS COCINAS INDUSTRIALES Y CONVENCIONALES 🌀🌀",
                "❎❎COCINAS INDUSTRIALES Y CONVENCIONALES OFERTAS!! HASTA AGOTAR STOCK❎❎",
                "🌀🌀COCINAS INDUSTRIALES Y CONVENCIONALES LIQUIDAMOS HASTA AGOTAR STOCK🌀🌀",
                "🌐🌐ULTIMAS UNIDADES COCINAS INDUSTRIALES Y CONVENCIONALES🌐🌐",
                "👻👻COCINAS INDUSTRIALES Y CONVENCIONALES OFERTA IMPERDIBLE👻👻",
                "🌊🌐LIQUIDAMOS COCINAS INDUSTRIALES Y CONVENCIONALES LAS MEJORES MARCAS AL MEJOR PRECIO 🌐🌊",
                "🔱🌀APROVECHE OFERTA LIMITADA COCINAS INDUSTRIALES Y CONVENCIONALES 🌀⚜",
                "🌀🌀liquidamos cocinas industriales y convencionales 🌀🌀",
                "❎❎cocinas industriales y convencionales ofertas!! hasta agotar stock❎❎",
                "🌀🌀cocinas industriales y convencionales liquidamos hasta agotar stock🌀🌀",
                "🌐🌐ultimas unidades cocinas industriales y convencionales🌐🌐",
                "👻👻cocinas industriales y convencionales oferta imperdible👻👻",
                "🌊🌐liquidamos cocinas industriales y convencionales las mejores marcas al mejor precio 🌐🌊",
                "🔱🌀aproveche oferta limitada cocinas industriales y convencionales 🌀⚜",
                "🔱🔱COCINAS INDUSTRIALES Y CONVENCIONALES OFERTAS EXCLUSIVAS🔱🔱",
                "💫💫Ofertas Exclusivas Cocinas Convencionales e Industrales 💫💫",
                "💫💫Aproveche Liquidacion de Cocinas Convencionales e Industrales 💫💫",
                "💫💫ofertas exclusivas cocinas industriales y convencionales💫💫",
                "💫💫aproveche liquidacion de cocinas industriales y convencionales💫💫",
                "💫💫OFERTAS EXCLUSIVAS COCINAS INDUSTRIALES Y CONVENCIONALES 💫💫",
                "💫💫APROVECHE LIQUIDACION DE COCINAS INDUSTRIALES Y CONVENCIONALES💫💫",
                "💫💫OFERTAS EXCLUSIVAS COCINAS INDUSTRIALES Y CONVENCIONALES 💫💫",
                "💫💫APROVECHE LIQUIDACION DE COCINAS INDUSTRIALES Y CONVENCIONALES 💫💫"]

def ObtenerTitulo(titulos):
    num = len(titulos) - 1
    indice = random.randint(0,num)
    return titulos[indice]
